### PR TITLE
fix: configure the XML parser to maintain child order

### LINKED ISSUE #46: report() - Node children respecting original node children order
Hi,

I'm curious if there was any way to configure the output of the children from the report function to respect the order of the nodes of an svg.

I use svgi as an intermediary layer to pull out the svg data to do the following; merging ThemeProvider color in, generating named TS definitions for each svg icon, and a few other things that is not important for this request 

Up until now I've only handled single layer svg's using `path`, however, I now have a new requirement of different elements, and I'm getting svgs show up incorrectly.

To get my point across, I have an example below which replicates the same issue.

I currently have an svg described by:
```
<svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
    <rect x="0" y="0" width="48" height="48" fill="yellow"/>
    <circle cx="24" cy="24" r="24" fill="red"/>
    <rect x="16" y="16" width="16" height="16" fill="blue"/>
</svg>
```

Which produces the following svg

test icon

```
const SVGI = require('svgi');
const { nodes } = new SVGI('filepath/to/test.svg').report();
console.log(nodes);
```

```
{
  type: 'svg',
  category: 'containers',
  properties: {
    width: '48',
    height: '48',
    viewBox: '0 0 48 48',
    fill: 'none',
    xmlns: 'http://www.w3.org/2000/svg'
  },
  children: [
    {
      type: 'rect',
      category: 'shapes',
      properties: [Object],
      children: []
    },
    {
      type: 'rect',
      category: 'shapes',
      properties: [Object],
      children: []
    },
    {
      type: 'circle',
      category: 'shapes',
      properties: [Object],
      children: []
    }
  ]
}
```

However, the rects have been grouped to the top, and produces the following shape

after test

Is there a way for the children to be as such:
```
{
      type: 'rect',
      category: 'shapes',
      properties: [Object],
      children: []
    },
    {
      type: 'circle',
      category: 'shapes',
      properties: [Object],
      children: []
    },
    {
      type: 'rect',
      category: 'shapes',
      properties: [Object],
      children: []
    }
```

Thank you,

Using svgi@v1.1.0

### PR DESCRIPTION
**Pull request by Angelmmiguel**
To fix this issue, I configured the XML parser with the following options:

```javascript
// Parser
const parser = new xml2js.Parser({ 
  preserveChildrenOrder: true, 
  explicitChildren: true 
});
```

This configuration adds a `$$` property to the nodes that represents an array of the children in the right order. I added a test to check it.

It closes #46

### CODE REVIEW

File: lib/svg.js [hunk 1]
```diff
@@ -5,7 +5,10 @@ const Node = require('./node');
 const {allCategories, allTypes} = require('./utils/nodeTypes');
 
 // Parser
-const parser = new xml2js.Parser();
+const parser = new xml2js.Parser({ 
+  preserveChildrenOrder: true,
```
Comment (rubberbandage) [inline lib/svg.js:9]: Not sure if this will be a breaking change for anyone currently using this library with preserveChildrenOrder defaulted to `false`

**Review by rubberbandage — APPROVED** [review]
🚀 Looking forward to these changes

File: lib/svg.js (hunk 1 above)
Comment (Angelmmiguel) [reply lib/svg.js:9]: It should only affect the cases where people rely on a wrong order. Since it's a wrong behavior and the SVGI API is the same, I would move forward with it :)
